import os
import sys

import pymysql
# Form implementation generated from reading ui file 'denglu2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QCoreApplication
from PyQt5.QtGui import QMovie, QIcon, QPixmap
from PyQt5.QtWidgets import QMainWindow, QVBoxLayout, QLabel, QWidget, QMessageBox, QDialog, QProgressBar
import Main


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 717)
        MainWindow.setStyleSheet("")
        # 设置窗口为无边框
        MainWindow.setWindowFlags(Qt.FramelessWindowHint)
        # 设置窗口背景为透明
        MainWindow.setAttribute(Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("font: 14pt \"微软雅黑\";")
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 90, 480, 140))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setStyleSheet("")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("pictures/2.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(260, 230, 481, 271))
        self.frame.setStyleSheet("background:white;\n"
"font: 14pt \"微软雅黑\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(120, 30, 261, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    border-bottom:1px solid rgb(229,229,229);\n"
"    color:black;\n"
"    \n"
"    font: 12pt \"Microsoft YaHei\";\n"
"}\n"
"QLineEdit:hover{\n"
"    border-bottom:1px solid rgb(193,193,193);\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom:1px solid rgb(18,183,245);\n"
"}")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 100, 261, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    border-bottom:1px solid rgb(229,229,229);\n"
"    color:black;\n"
"    font: 12pt \"Microsoft YaHei\";\n"
"}\n"
"QLineEdit:hover{\n"
"    border-bottom:1px solid rgb(193,193,193);\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom:1px solid rgb(18,183,245);\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(100, 200, 281, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    color:rgb(0, 0, 0);\n"
"    background:rgb(0, 170, 255);\n"
"    color:white;\n"
"    font: 16pt \"楷体\";\n"
"background-color:\n"
"qlineargradient(spread:pad,x1:0,x2:0, y1:0, y2:1,\n"
"stop: 0 rgb(0, 170, 255),\n"
"stop: 0.495 rgb(0, 170, 255),\n"
"stop: 0.505 rgb(0, 170, 255),\n"
"stop: 1 rgb(0, 170, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:\n"
"qlineargradient(spread:pad,x1:0,x2:0, y1:0, y2:1,\n"
"stop: 0 rgb(0, 135, 203),\n"
"stop: 0.495 rgb(0, 135, 203),\n"
"stop: 0.505 rgb(0, 135, 203),\n"
"stop: 1 rgb(0, 135, 203));\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pictures/安全登录.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(18, 18))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 160, 81, 21))
        self.label.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    color:rgb(0, 0, 0);\n"
"    font: 11pt \"Agency FB\";\n"
"}\n"
"QLabel:hover{\n"
"    color:rgb(18,183,245);\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(310, 160, 71, 21))
        self.label_2.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    color:rgb(0, 0, 0);\n"
"    font: 12pt \"Agency FB\";\n"
"}\n"
"QLabel:hover{\n"
"    color:rgb(18,183,245);\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(90, 35, 25, 25))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("pictures/用户名.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(90, 105, 25, 25))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("pictures/密码.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(350, 30, 20, 20))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("pictures/下尖号.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(350, 100, 21, 21))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("pictures/键盘.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(450, 240, 31, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("pictures/二维码.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(700, 90, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,84,57);\n"
"}")
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pictures/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(660, 90, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(190,190,190,200);\n"
"}")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pictures/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(380, 120, 221, 81))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("pictures/titlelogo.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "板探智眸"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "用户名"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "密码"))
        self.pushButton.setText(_translate("MainWindow", "安全登录"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>项目官网</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">管理后台</span></p></body></html>"))

        # 将登录按钮与登录方法绑定
        self.pushButton.clicked.connect(self.login)

    def login(self):
        # 连接数据库
        conn = pymysql.connect(host='localhost', port=3306, user='root', password='123456', database='simpleui',
                               charset='utf8')
        cursor = conn.cursor()

        name = self.lineEdit.text()
        phone = self.lineEdit_2.text()

        # 查询数据库
        sql = "SELECT * FROM demo_employe WHERE name=%s AND phone=%s"
        cursor.execute(sql, (name, phone))
        result = cursor.fetchall()

        if result:
            # 用户名密码匹配成功，打开新窗口
            # main_window = main.MainWindow()
            main_window.show()
            main_window.pushButton_14.clicked.connect(main_window.click_pushButton_14)
            # main_window.lineEdit.setText(name)    # 显示用户名
            print('success!')
            # 关闭登录窗口
            window.close()
        else:
            # 用户名或密码错误
            print("用户名或密码错误")
            # 创建QMessageBox实例
            msg_box = QMessageBox()
            msg_box.setIcon(QMessageBox.Warning)
            msg_box.setText("登录失败！请检查用户名或密码")
            msg_box.setWindowTitle("登录错误")
            msg_box.setStandardButtons(QMessageBox.Ok)

            # 显示消息框，并等待用户响应
            msg_box.exec_()

            # 关闭数据库连接
        cursor.close()
        conn.close()

class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        self.setupUi(self)

        # 最小化、关闭窗口
        self.pushButton_3.clicked.connect(self.click_pushButton_3)
        self.pushButton_4.clicked.connect(self.click_pushButton_4)
        # 跳转到项目官网
        self.label.mouseReleaseEvent = self.JumpToWebsite
        # 跳转到登录页面
        self.label_2.mouseReleaseEvent = self.JumpToLogin

    def click_pushButton_3(self):
        self.showMinimized()

    def click_pushButton_4(self):
        self.close()

    #创建跳转到项目官网的函数,地址：https://wangsuhang123.github.io/btzm/index.html
    def JumpToWebsite(self, event):
        import webbrowser
        webbrowser.open('https://wangsuhang123.github.io/btzm/index.html')

    #创建跳转到登录页面的函数
    def JumpToLogin(self, event):
        import webbrowser
        webbrowser.open('http://127.0.0.1:8000/#/demo/employe/')


class LoadingDialog(QDialog):
    def __init__(self):
        super().__init__()
        # 设置图标
        self.setWindowIcon(QtGui.QIcon("pictures/fangfajing.png"))
        self.setWindowTitle("板探智眸")
        self.setGeometry(600, 300, 300, 100)

        # 计算并设置窗口位置到屏幕中心
        screen = QtWidgets.QDesktopWidget().screenGeometry()
        x = (screen.width() - self.width()) // 2
        y = (screen.height() - self.height()) // 2
        self.move(x, y)

        layout = QVBoxLayout()
        self.label = QLabel("程序加载中，请稍后...")
        layout.addWidget(self.label)
        self.progressBar = QProgressBar()
        self.progressBar.setRange(0, 0)  # 设置进度条为不确定状态
        layout.addWidget(self.progressBar)
        self.setLayout(layout)

if __name__ == "__main__":
    QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QtWidgets.QApplication(sys.argv)

    loading_dialog = LoadingDialog()
    loading_dialog.show()

    # 更新界面，确保弹窗及时显示
    app.processEvents()

    # 设置计时器，12秒后关闭弹窗并显示主窗口
    QtCore.QTimer.singleShot(12000, lambda: (loading_dialog.close(), window.show()))

    window = MainWindow()
    main_window = Main.MainWindow()
    # 设置窗口图标
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("pictures/fangfajing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    window.setWindowIcon(icon)

    sys.exit(app.exec_())