import sys

from PyQt5.QtCore import QCoreApplication, QDateTime, QTimer
import cv2
import torch
import numpy as np
from PIL import Image
from PyQt5.QtGui import QImage, QPixmap, QIcon
from PyQt5.QtWidgets import QMainWindow, QMessageBox
import time  # 需要这个库生成独特的文件名
import openpyxl as op
from VideoDetect import VideoDetect
from unet import UNet
import threading

import Setting
import pdf
import speak

from camera import Camera
from dataShow import *
from deleteAll import *
from global_store import shared_data
from imageDetect import ImageDetect


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

import ctypes
ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("myappid")
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1403, 845)
        MainWindow.setStyleSheet("")

        MainWindow.setWindowIcon(QIcon("DetectionSystem2/pictures/fangfajing.png"))
        MainWindow.setWindowIcon(QIcon("pictures/fangfajing.ico"))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("font: 16pt \"微软雅黑\";")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.frame_2.setStyleSheet("QFrame{\n"
"    border:1px solid rgb(0, 93, 139,90%);\n"
"    background:rgb(0, 93, 139,90%);\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    background:rgb(0, 93, 139,90%);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255,30%);\n"
"    padding: 5px;\n"
"    border-left: 2px solid rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(255, 255, 255,30%);\n"
"    padding: 5px;\n"
"    border-left: 2px solid rgb(255, 255, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(70, 80))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setStyleSheet("border:none;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_7.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pictures/图像.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_8.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pictures/7实时监测.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_10.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pictures/视频1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon2)
        self.pushButton_10.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_9.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pictures/数据可视化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_14.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("pictures/设置.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon4)
        self.pushButton_14.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_2.addWidget(self.pushButton_14)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(80, 328))
        self.label_6.setStyleSheet("border:none;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_6.raise_()
        self.label_5.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_10.raise_()
        self.pushButton_14.raise_()
        self.pushButton_9.raise_()
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setStyleSheet("border:none;\n"
"border-left:1px solid rgb(0, 93, 139,90%);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_4.setStyleSheet("QFrame{\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setMinimumSize(QtCore.QSize(0, 80))
        self.label_4.setStyleSheet("border:none;\n"
"font: 48pt \"华文行楷\";\n"
"color:white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(QDateTime.currentDateTime(),self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit.setSizePolicy(sizePolicy)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(30, 70))
        self.dateTimeEdit.setStyleSheet("background-color:rgb(0, 93, 139,90%);\n"
"border:none;\n"
"color:white;")
        self.dateTimeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateTimeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_11.addWidget(self.dateTimeEdit)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(30, 70))
        self.lineEdit.setStyleSheet("background-color:rgb(0, 93, 139,90%);\n"
"border:none;\n"
"color:white;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_11.addWidget(self.lineEdit)
        self.horizontalLayout_11.setStretch(0, 8)
        self.horizontalLayout_11.setStretch(1, 2)
        self.horizontalLayout_11.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("background:rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWidget.setStyleSheet("border:none;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setContentsMargins(6, 9, 6, 9)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setStyleSheet("border:none;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(125, 55))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background:rgb(0, 93, 139,90%);\n"
"    color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 153, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(125, 55))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background:rgb(0, 93, 139,90%);\n"
"    color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 153, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(125, 55))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background:rgb(0, 93, 139,90%);\n"
"    color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 153, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_4.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setMinimumSize(QtCore.QSize(125, 55))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background:rgb(0, 93, 139,90%);\n"
"    color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 153, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_4.addWidget(self.pushButton_13)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_12 = QtWidgets.QFrame(self.frame_7)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_5.setContentsMargins(11, -1, 11, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(40, 40))
        self.label_9.setStyleSheet("border:1px solid black;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(40, 40))
        self.label_10.setStyleSheet("border:1px solid black;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.verticalLayout_3.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(125, 55))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background:rgb(0, 93, 139,90%);\n"
"    color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 153, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(125, 55))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background:rgb(0, 93, 139,90%);\n"
"    color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 153, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(125, 55))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background:rgb(0, 93, 139,90%);\n"
"    color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 153, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 4)
        self.verticalLayout_3.setStretch(2, 1)
        self.frame_12.raise_()
        self.frame_11.raise_()
        self.frame_10.raise_()
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("border:1px solid black;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_19 = QtWidgets.QLabel(self.frame_9)
        self.label_19.setStyleSheet("border:none;")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_14.addWidget(self.label_19)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_14.addWidget(self.lineEdit_11)
        self.horizontalLayout_14.setStretch(0, 3)
        self.horizontalLayout_14.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.frame_9)
        self.label_14.setStyleSheet("border:none;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_19.sizePolicy().hasHeightForWidth())
        self.lineEdit_19.setSizePolicy(sizePolicy)
        self.lineEdit_19.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_13.addWidget(self.lineEdit_19)
        self.horizontalLayout_13.setStretch(0, 3)
        self.horizontalLayout_13.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_15 = QtWidgets.QLabel(self.frame_9)
        self.label_15.setStyleSheet("border:none;")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_22.addWidget(self.label_15)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_22.addWidget(self.lineEdit_2)
        self.horizontalLayout_22.setStretch(0, 3)
        self.horizontalLayout_22.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_16 = QtWidgets.QLabel(self.frame_9)
        self.label_16.setStyleSheet("border:none;")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_23.addWidget(self.label_16)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_23.addWidget(self.lineEdit_3)
        self.horizontalLayout_23.setStretch(0, 3)
        self.horizontalLayout_23.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_22 = QtWidgets.QLabel(self.frame_9)
        self.label_22.setStyleSheet("border:none;")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_24.addWidget(self.label_22)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_14.setSizePolicy(sizePolicy)
        self.lineEdit_14.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_24.addWidget(self.lineEdit_14)
        self.horizontalLayout_24.setStretch(0, 3)
        self.horizontalLayout_24.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_21 = QtWidgets.QLabel(self.frame_9)
        self.label_21.setStyleSheet("border:none;")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_25.addWidget(self.label_21)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_25.addWidget(self.lineEdit_8)
        self.horizontalLayout_25.setStretch(0, 3)
        self.horizontalLayout_25.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_20 = QtWidgets.QLabel(self.frame_9)
        self.label_20.setStyleSheet("border:none;")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_26.addWidget(self.label_20)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_18.sizePolicy().hasHeightForWidth())
        self.lineEdit_18.setSizePolicy(sizePolicy)
        self.lineEdit_18.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_26.addWidget(self.lineEdit_18)
        self.horizontalLayout_26.setStretch(0, 3)
        self.horizontalLayout_26.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_17 = QtWidgets.QLabel(self.frame_9)
        self.label_17.setStyleSheet("border:none;")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_27.addWidget(self.label_17)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_27.addWidget(self.lineEdit_4)
        self.horizontalLayout_27.setStretch(0, 3)
        self.horizontalLayout_27.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_18 = QtWidgets.QLabel(self.frame_9)
        self.label_18.setStyleSheet("border:none;")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_28.addWidget(self.label_18)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_16.sizePolicy().hasHeightForWidth())
        self.lineEdit_16.setSizePolicy(sizePolicy)
        self.lineEdit_16.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_28.addWidget(self.lineEdit_16)
        self.horizontalLayout_28.setStretch(0, 3)
        self.horizontalLayout_28.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_25 = QtWidgets.QLabel(self.frame_9)
        self.label_25.setStyleSheet("border:none;")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_29.addWidget(self.label_25)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_29.addWidget(self.lineEdit_5)
        self.horizontalLayout_29.setStretch(0, 3)
        self.horizontalLayout_29.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_26 = QtWidgets.QLabel(self.frame_9)
        self.label_26.setStyleSheet("border:none;")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_30.addWidget(self.label_26)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_30.addWidget(self.lineEdit_6)
        self.horizontalLayout_30.setStretch(0, 3)
        self.horizontalLayout_30.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_27 = QtWidgets.QLabel(self.frame_9)
        self.label_27.setStyleSheet("border:none;")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_31.addWidget(self.label_27)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_15.sizePolicy().hasHeightForWidth())
        self.lineEdit_15.setSizePolicy(sizePolicy)
        self.lineEdit_15.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_31.addWidget(self.lineEdit_15)
        self.horizontalLayout_31.setStretch(0, 3)
        self.horizontalLayout_31.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_28 = QtWidgets.QLabel(self.frame_9)
        self.label_28.setStyleSheet("border:none;")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_32.addWidget(self.label_28)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_17.sizePolicy().hasHeightForWidth())
        self.lineEdit_17.setSizePolicy(sizePolicy)
        self.lineEdit_17.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_32.addWidget(self.lineEdit_17)
        self.horizontalLayout_32.setStretch(0, 3)
        self.horizontalLayout_32.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_29 = QtWidgets.QLabel(self.frame_9)
        self.label_29.setStyleSheet("border:none;")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_33.addWidget(self.label_29)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_13.sizePolicy().hasHeightForWidth())
        self.lineEdit_13.setSizePolicy(sizePolicy)
        self.lineEdit_13.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_33.addWidget(self.lineEdit_13)
        self.horizontalLayout_33.setStretch(0, 3)
        self.horizontalLayout_33.setStretch(1, 6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.horizontalLayout_2.setStretch(0, 6)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.verticalLayout_4.setStretch(0, 7)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_13 = QtWidgets.QFrame(self.page_2)
        self.frame_13.setStyleSheet("border:none;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.frame_13)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_15 = QtWidgets.QFrame(self.frame_8)
        self.frame_15.setStyleSheet("border:none;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_9.setContentsMargins(18, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.frame_15)
        self.label_8.setStyleSheet("border:1px solid black;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.horizontalLayout_8.addWidget(self.frame_15)
        self.frame_18 = QtWidgets.QFrame(self.frame_8)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_5.setContentsMargins(8, 0, 12, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.frame_18)
        self.label_12.setStyleSheet("border:1px solid black;")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.frame_18)
        self.label_13.setStyleSheet("border:1px solid black;")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.horizontalLayout_8.addWidget(self.frame_18)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.frame_19 = QtWidgets.QFrame(self.frame_13)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_7.setContentsMargins(18, 5, 11, 11)
        self.horizontalLayout_7.setSpacing(7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(125, 70))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background:rgb(0, 93, 139,90%);\n"
"    color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 153, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(125, 70))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background:rgb(0, 93, 139,90%);\n"
"    color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 153, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.verticalLayout_6.addWidget(self.frame_19)
        self.verticalLayout_6.setStretch(0, 8)
        self.verticalLayout_6.setStretch(1, 2)
        self.horizontalLayout_3.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.page_2)
        self.frame_14.setStyleSheet("border:none;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setStyleSheet("border:1px solid black;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_23 = QtWidgets.QLabel(self.frame_16)
        self.label_23.setStyleSheet("border:none;")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_15.addWidget(self.label_23)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_15.addWidget(self.lineEdit_12)
        self.horizontalLayout_15.setStretch(0, 3)
        self.horizontalLayout_15.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_24 = QtWidgets.QLabel(self.frame_16)
        self.label_24.setStyleSheet("border:none;")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_16.addWidget(self.label_24)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_20.sizePolicy().hasHeightForWidth())
        self.lineEdit_20.setSizePolicy(sizePolicy)
        self.lineEdit_20.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_16.addWidget(self.lineEdit_20)
        self.horizontalLayout_16.setStretch(0, 3)
        self.horizontalLayout_16.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_30 = QtWidgets.QLabel(self.frame_16)
        self.label_30.setStyleSheet("border:none;")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_34.addWidget(self.label_30)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_34.addWidget(self.lineEdit_7)
        self.horizontalLayout_34.setStretch(0, 3)
        self.horizontalLayout_34.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_31 = QtWidgets.QLabel(self.frame_16)
        self.label_31.setStyleSheet("border:none;")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_35.addWidget(self.label_31)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_35.addWidget(self.lineEdit_9)
        self.horizontalLayout_35.setStretch(0, 3)
        self.horizontalLayout_35.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_32 = QtWidgets.QLabel(self.frame_16)
        self.label_32.setStyleSheet("border:none;")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_36.addWidget(self.label_32)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_21.sizePolicy().hasHeightForWidth())
        self.lineEdit_21.setSizePolicy(sizePolicy)
        self.lineEdit_21.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_36.addWidget(self.lineEdit_21)
        self.horizontalLayout_36.setStretch(0, 3)
        self.horizontalLayout_36.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_33 = QtWidgets.QLabel(self.frame_16)
        self.label_33.setStyleSheet("border:none;")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_37.addWidget(self.label_33)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_37.addWidget(self.lineEdit_10)
        self.horizontalLayout_37.setStretch(0, 3)
        self.horizontalLayout_37.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_34 = QtWidgets.QLabel(self.frame_16)
        self.label_34.setStyleSheet("border:none;")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_38.addWidget(self.label_34)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_22.sizePolicy().hasHeightForWidth())
        self.lineEdit_22.setSizePolicy(sizePolicy)
        self.lineEdit_22.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_38.addWidget(self.lineEdit_22)
        self.horizontalLayout_38.setStretch(0, 3)
        self.horizontalLayout_38.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_35 = QtWidgets.QLabel(self.frame_16)
        self.label_35.setStyleSheet("border:none;")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_39.addWidget(self.label_35)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_23.sizePolicy().hasHeightForWidth())
        self.lineEdit_23.setSizePolicy(sizePolicy)
        self.lineEdit_23.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_39.addWidget(self.lineEdit_23)
        self.horizontalLayout_39.setStretch(0, 3)
        self.horizontalLayout_39.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_36 = QtWidgets.QLabel(self.frame_16)
        self.label_36.setStyleSheet("border:none;")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_40.addWidget(self.label_36)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_24.sizePolicy().hasHeightForWidth())
        self.lineEdit_24.setSizePolicy(sizePolicy)
        self.lineEdit_24.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_40.addWidget(self.lineEdit_24)
        self.horizontalLayout_40.setStretch(0, 3)
        self.horizontalLayout_40.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_37 = QtWidgets.QLabel(self.frame_16)
        self.label_37.setStyleSheet("border:none;")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_41.addWidget(self.label_37)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_25.sizePolicy().hasHeightForWidth())
        self.lineEdit_25.setSizePolicy(sizePolicy)
        self.lineEdit_25.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_41.addWidget(self.lineEdit_25)
        self.horizontalLayout_41.setStretch(0, 3)
        self.horizontalLayout_41.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_38 = QtWidgets.QLabel(self.frame_16)
        self.label_38.setStyleSheet("border:none;")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_42.addWidget(self.label_38)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_26.sizePolicy().hasHeightForWidth())
        self.lineEdit_26.setSizePolicy(sizePolicy)
        self.lineEdit_26.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_42.addWidget(self.lineEdit_26)
        self.horizontalLayout_42.setStretch(0, 3)
        self.horizontalLayout_42.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_39 = QtWidgets.QLabel(self.frame_16)
        self.label_39.setStyleSheet("border:none;")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_43.addWidget(self.label_39)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_27.sizePolicy().hasHeightForWidth())
        self.lineEdit_27.setSizePolicy(sizePolicy)
        self.lineEdit_27.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.horizontalLayout_43.addWidget(self.lineEdit_27)
        self.horizontalLayout_43.setStretch(0, 3)
        self.horizontalLayout_43.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_40 = QtWidgets.QLabel(self.frame_16)
        self.label_40.setStyleSheet("border:none;")
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_44.addWidget(self.label_40)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_28.sizePolicy().hasHeightForWidth())
        self.lineEdit_28.setSizePolicy(sizePolicy)
        self.lineEdit_28.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.horizontalLayout_44.addWidget(self.lineEdit_28)
        self.horizontalLayout_44.setStretch(0, 3)
        self.horizontalLayout_44.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_41 = QtWidgets.QLabel(self.frame_16)
        self.label_41.setStyleSheet("border:none;")
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_45.addWidget(self.label_41)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_29.sizePolicy().hasHeightForWidth())
        self.lineEdit_29.setSizePolicy(sizePolicy)
        self.lineEdit_29.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.horizontalLayout_45.addWidget(self.lineEdit_29)
        self.horizontalLayout_45.setStretch(0, 3)
        self.horizontalLayout_45.setStretch(1, 6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_17.addWidget(self.frame_16)
        self.horizontalLayout_3.addWidget(self.frame_14)
        self.horizontalLayout_3.setStretch(0, 6)
        self.horizontalLayout_3.setStretch(1, 4)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_17 = QtWidgets.QFrame(self.page_3)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_18.setSpacing(11)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_20 = QtWidgets.QFrame(self.frame_17)
        self.frame_20.setStyleSheet("border:none;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_20.setContentsMargins(11, 0, 11, 11)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_11 = QtWidgets.QLabel(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(40, 40))
        self.label_11.setStyleSheet("border:1px solid black;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_20.addWidget(self.label_11)
        self.label_42 = QtWidgets.QLabel(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setMinimumSize(QtCore.QSize(40, 40))
        self.label_42.setStyleSheet("border:1px solid black;")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_20.addWidget(self.label_42)
        self.verticalLayout_9.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.frame_20)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_21.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_21.setSpacing(7)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setMinimumSize(QtCore.QSize(125, 55))
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background:rgb(0, 93, 139,90%);\n"
"    color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 153, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_21.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setMinimumSize(QtCore.QSize(125, 55))
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background:rgb(0, 93, 139,90%);\n"
"    color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 153, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_21.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setMinimumSize(QtCore.QSize(125, 55))
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background:rgb(0, 93, 139,90%);\n"
"    color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 153, 230);\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(0, 93, 139,90%);\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_21.addWidget(self.pushButton_21)
        self.verticalLayout_9.addWidget(self.frame_23)
        self.verticalLayout_9.setStretch(0, 4)
        self.verticalLayout_9.setStretch(1, 1)
        self.horizontalLayout_18.addWidget(self.frame_20)
        self.frame_24 = QtWidgets.QFrame(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_24.sizePolicy().hasHeightForWidth())
        self.frame_24.setSizePolicy(sizePolicy)
        self.frame_24.setStyleSheet("border:1px solid black;")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_46.setSpacing(6)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_43 = QtWidgets.QLabel(self.frame_24)
        self.label_43.setStyleSheet("border:none;")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_46.addWidget(self.label_43)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_30.sizePolicy().hasHeightForWidth())
        self.lineEdit_30.setSizePolicy(sizePolicy)
        self.lineEdit_30.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.horizontalLayout_46.addWidget(self.lineEdit_30)
        self.horizontalLayout_46.setStretch(0, 3)
        self.horizontalLayout_46.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_44 = QtWidgets.QLabel(self.frame_24)
        self.label_44.setStyleSheet("border:none;")
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_47.addWidget(self.label_44)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_31.sizePolicy().hasHeightForWidth())
        self.lineEdit_31.setSizePolicy(sizePolicy)
        self.lineEdit_31.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.horizontalLayout_47.addWidget(self.lineEdit_31)
        self.horizontalLayout_47.setStretch(0, 3)
        self.horizontalLayout_47.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_45 = QtWidgets.QLabel(self.frame_24)
        self.label_45.setStyleSheet("border:none;")
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_48.addWidget(self.label_45)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_32.sizePolicy().hasHeightForWidth())
        self.lineEdit_32.setSizePolicy(sizePolicy)
        self.lineEdit_32.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.horizontalLayout_48.addWidget(self.lineEdit_32)
        self.horizontalLayout_48.setStretch(0, 3)
        self.horizontalLayout_48.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_46 = QtWidgets.QLabel(self.frame_24)
        self.label_46.setStyleSheet("border:none;")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_49.addWidget(self.label_46)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_33.sizePolicy().hasHeightForWidth())
        self.lineEdit_33.setSizePolicy(sizePolicy)
        self.lineEdit_33.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.horizontalLayout_49.addWidget(self.lineEdit_33)
        self.horizontalLayout_49.setStretch(0, 3)
        self.horizontalLayout_49.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_47 = QtWidgets.QLabel(self.frame_24)
        self.label_47.setStyleSheet("border:none;")
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_50.addWidget(self.label_47)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_34.sizePolicy().hasHeightForWidth())
        self.lineEdit_34.setSizePolicy(sizePolicy)
        self.lineEdit_34.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.horizontalLayout_50.addWidget(self.lineEdit_34)
        self.horizontalLayout_50.setStretch(0, 3)
        self.horizontalLayout_50.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_48 = QtWidgets.QLabel(self.frame_24)
        self.label_48.setStyleSheet("border:none;")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_51.addWidget(self.label_48)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_35.sizePolicy().hasHeightForWidth())
        self.lineEdit_35.setSizePolicy(sizePolicy)
        self.lineEdit_35.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.horizontalLayout_51.addWidget(self.lineEdit_35)
        self.horizontalLayout_51.setStretch(0, 3)
        self.horizontalLayout_51.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_49 = QtWidgets.QLabel(self.frame_24)
        self.label_49.setStyleSheet("border:none;")
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_52.addWidget(self.label_49)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_36.sizePolicy().hasHeightForWidth())
        self.lineEdit_36.setSizePolicy(sizePolicy)
        self.lineEdit_36.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.horizontalLayout_52.addWidget(self.lineEdit_36)
        self.horizontalLayout_52.setStretch(0, 3)
        self.horizontalLayout_52.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_50 = QtWidgets.QLabel(self.frame_24)
        self.label_50.setStyleSheet("border:none;")
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_53.addWidget(self.label_50)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_37.sizePolicy().hasHeightForWidth())
        self.lineEdit_37.setSizePolicy(sizePolicy)
        self.lineEdit_37.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.horizontalLayout_53.addWidget(self.lineEdit_37)
        self.horizontalLayout_53.setStretch(0, 3)
        self.horizontalLayout_53.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_51 = QtWidgets.QLabel(self.frame_24)
        self.label_51.setStyleSheet("border:none;")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_54.addWidget(self.label_51)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_38.sizePolicy().hasHeightForWidth())
        self.lineEdit_38.setSizePolicy(sizePolicy)
        self.lineEdit_38.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.horizontalLayout_54.addWidget(self.lineEdit_38)
        self.horizontalLayout_54.setStretch(0, 3)
        self.horizontalLayout_54.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_52 = QtWidgets.QLabel(self.frame_24)
        self.label_52.setStyleSheet("border:none;")
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_55.addWidget(self.label_52)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_39.sizePolicy().hasHeightForWidth())
        self.lineEdit_39.setSizePolicy(sizePolicy)
        self.lineEdit_39.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.horizontalLayout_55.addWidget(self.lineEdit_39)
        self.horizontalLayout_55.setStretch(0, 3)
        self.horizontalLayout_55.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_53 = QtWidgets.QLabel(self.frame_24)
        self.label_53.setStyleSheet("border:none;")
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_56.addWidget(self.label_53)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_40.sizePolicy().hasHeightForWidth())
        self.lineEdit_40.setSizePolicy(sizePolicy)
        self.lineEdit_40.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.horizontalLayout_56.addWidget(self.lineEdit_40)
        self.horizontalLayout_56.setStretch(0, 3)
        self.horizontalLayout_56.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_56)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_54 = QtWidgets.QLabel(self.frame_24)
        self.label_54.setStyleSheet("border:none;")
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_57.addWidget(self.label_54)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_41.sizePolicy().hasHeightForWidth())
        self.lineEdit_41.setSizePolicy(sizePolicy)
        self.lineEdit_41.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.horizontalLayout_57.addWidget(self.lineEdit_41)
        self.horizontalLayout_57.setStretch(0, 3)
        self.horizontalLayout_57.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_55 = QtWidgets.QLabel(self.frame_24)
        self.label_55.setStyleSheet("border:none;")
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_58.addWidget(self.label_55)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_42.sizePolicy().hasHeightForWidth())
        self.lineEdit_42.setSizePolicy(sizePolicy)
        self.lineEdit_42.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.horizontalLayout_58.addWidget(self.lineEdit_42)
        self.horizontalLayout_58.setStretch(0, 3)
        self.horizontalLayout_58.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_56 = QtWidgets.QLabel(self.frame_24)
        self.label_56.setStyleSheet("border:none;")
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_59.addWidget(self.label_56)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_43.sizePolicy().hasHeightForWidth())
        self.lineEdit_43.setSizePolicy(sizePolicy)
        self.lineEdit_43.setStyleSheet("border:1px solid black;\n"
"background-color:rgb(255, 255, 255);")
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.horizontalLayout_59.addWidget(self.lineEdit_43)
        self.horizontalLayout_59.setStretch(0, 3)
        self.horizontalLayout_59.setStretch(1, 6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_18.addWidget(self.frame_24)
        self.horizontalLayout_18.setStretch(0, 6)
        self.horizontalLayout_18.setStretch(1, 4)
        self.horizontalLayout_19.addWidget(self.frame_17)
        self.horizontalLayout_19.setStretch(0, 6)
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout_10.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        self.horizontalLayout.addWidget(self.frame_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 9)
        self.horizontalLayout_12.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1403, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "玻影智鉴"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">“玻影智鉴”玻璃缺陷检测系统</span></p></body></html>"))
        self.lineEdit.setText(_translate("MainWindow", "检测"))
        self.pushButton.setText(_translate("MainWindow", "载入图片"))
        self.pushButton_11.setText(_translate("MainWindow", "载入文件"))
        self.pushButton_12.setText(_translate("MainWindow", "生成报告"))
        self.pushButton_13.setText(_translate("MainWindow", "保存图片"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">载入图片</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">标记图片</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "上一页"))
        self.pushButton_4.setText(_translate("MainWindow", "下一页"))
        self.pushButton_5.setText(_translate("MainWindow", "开始检测"))
        self.label_19.setText(_translate("MainWindow", "缺陷类别"))
        self.label_14.setText(_translate("MainWindow", "缺陷数量"))
        self.label_15.setText(_translate("MainWindow", "检测时间(s):"))
        self.label_16.setText(_translate("MainWindow", "准确率(%):"))
        self.label_22.setText(_translate("MainWindow", "缺陷位置:"))
        self.label_21.setText(_translate("MainWindow", "损伤程度:"))
        self.label_20.setText(_translate("MainWindow", "板坯级别:"))
        self.label_17.setText(_translate("MainWindow", "板坯数量"))
        self.label_18.setText(_translate("MainWindow", "A级板数量:"))
        self.label_25.setText(_translate("MainWindow", "B级板数量:"))
        self.label_26.setText(_translate("MainWindow", "C级板数量:"))
        self.label_27.setText(_translate("MainWindow", "缺陷面积(mm²):"))
        self.label_28.setText(_translate("MainWindow", "面积占比(%):"))
        self.label_29.setText(_translate("MainWindow", "A级板占比(%):"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">原始摄像头信息</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">拍摄图片</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">标记图片</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "开始检测"))
        self.pushButton_6.setText(_translate("MainWindow", "停止检测"))
        self.label_23.setText(_translate("MainWindow", "缺陷类别:"))
        self.label_24.setText(_translate("MainWindow", "缺陷数量:"))
        self.label_30.setText(_translate("MainWindow", "检测时间(s):"))
        self.label_31.setText(_translate("MainWindow", "准确率(%):"))
        self.label_32.setText(_translate("MainWindow", "缺陷位置:"))
        self.label_33.setText(_translate("MainWindow", "损伤程度:"))
        self.label_34.setText(_translate("MainWindow", "板坯级别:"))
        self.label_35.setText(_translate("MainWindow", "板坯数量:"))
        self.label_36.setText(_translate("MainWindow", "A级板数量:"))
        self.label_37.setText(_translate("MainWindow", "B级板数量:"))
        self.label_38.setText(_translate("MainWindow", "C级板数量:"))
        self.label_39.setText(_translate("MainWindow", "缺陷面积(m²):"))
        self.label_40.setText(_translate("MainWindow", "面积占比(%):"))
        self.label_41.setText(_translate("MainWindow", "A级板占比(%):"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">原视频</p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">检测视频</p></body></html>"))
        self.pushButton_19.setText(_translate("MainWindow", "导入视频"))
        self.pushButton_20.setText(_translate("MainWindow", "开始检测"))
        self.pushButton_21.setText(_translate("MainWindow", "停止检测"))
        self.label_43.setText(_translate("MainWindow", "缺陷类别"))
        self.label_44.setText(_translate("MainWindow", "缺陷数量"))
        self.label_45.setText(_translate("MainWindow", "检测时间(s):"))
        self.label_46.setText(_translate("MainWindow", "准确率(%):"))
        self.label_47.setText(_translate("MainWindow", "缺陷位置:"))
        self.label_48.setText(_translate("MainWindow", "损伤程度:"))
        self.label_49.setText(_translate("MainWindow", "板坯级别:"))
        self.label_50.setText(_translate("MainWindow", "板坯数量"))
        self.label_51.setText(_translate("MainWindow", "A级板数量:"))
        self.label_52.setText(_translate("MainWindow", "B级板数量:"))
        self.label_53.setText(_translate("MainWindow", "C级板数量:"))
        self.label_54.setText(_translate("MainWindow", "缺陷面积(mm²):"))
        self.label_55.setText(_translate("MainWindow", "面积占比(%):"))
        self.label_56.setText(_translate("MainWindow", "A级板占比(%):"))

        self.pushButton_7.clicked.connect(self.click_pushButton_7)
        self.pushButton_8.clicked.connect(self.click_pushButton_8)
        self.pushButton_10.clicked.connect(self.click_pushButton_10)


    def click_pushButton_7(self):
        self.stackedWidget.setCurrentIndex(0)
        self.lineEdit.setText("图像检测")

    def click_pushButton_8(self):
        self.stackedWidget.setCurrentIndex(1)
        self.lineEdit.setText("实时检测")

    def click_pushButton_10(self):
        self.stackedWidget.setCurrentIndex(2)
        self.lineEdit.setText("视频检测")


class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)

        self.setupUi(self)




if __name__ == "__main__":
    QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    # second_window = 设置.MainWindow()
    window.show()
    sys.exit(app.exec_())
